apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  targetNamespace: cilium-system
  interval: 10m
  timeout: 5m

  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/cilium
  prune: true
  wait: true
