apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  serviceAccountName: cluster-reconciler
  interval: 1h
  timeout: 5m

  chart:
    spec:
      chart: base
      version: "1.30.3"
      sourceRef:
        kind: HelmRepository
        name: istio
  install:
    crds: Create
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    defaultRevision: 1-30-3

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  serviceAccountName: cluster-reconciler
  interval: 1h
  timeout: 5m

  dependsOn:
    - name: istio-base

  chart:
    spec:
      chart: cni
      version: "1.30.3"
      sourceRef:
        kind: HelmRepository
        name: istio
  values:
    profile: ambient

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod-1-30-3
  namespace: istio-system
spec:
  serviceAccountName: cluster-reconciler
  interval: 1h
  timeout: 5m

  dependsOn:
    - name: istio-cni

  chart:
    spec:
      chart: istiod
      version: "1.30.3"
      sourceRef:
        kind: HelmRepository
        name: istio
  values:
    revision: 1-30-3
    profile: ambient

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  serviceAccountName: cluster-reconciler
  interval: 1h
  timeout: 5m

  dependsOn:
    - name: istiod-1-30-3

  chart:
    spec:
      chart: ztunnel
      version: "1.30.3"
      sourceRef:
        kind: HelmRepository
        name: istio
  values:
    revision: 1-30-3
