apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml

replacements:
  - source:
      kind: Namespace
      fieldPath: metadata.name
    targets:
      # Set ServiceAccount namespace.
      - select:
          kind: ServiceAccount
          name: cluster-reconciler
        fieldPaths:
          - metadata.namespace
      # Set ClusterRoleBinding subject namespace.
      - select:
          kind: ClusterRoleBinding
          name: cluster-reconciler
        fieldPaths:
          - subjects.[name=cluster-reconciler].namespace
      # Change ClusterRoleBinding name to "cluster-reconciler-${namespace}".
      # ClusterRoleBinding is cluster-scope so its name must be unique.
      - select:
          kind: ClusterRoleBinding
          name: cluster-reconciler
        fieldPaths:
          - metadata.name
        options:
          delimiter: "-"
          index: 2
