apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml

replacements:
  - source:
      kind: Namespace
      fieldPath: metadata.name
    targets:
      # Set ServiceAccount namespace.
      - select:
          kind: ServiceAccount
          name: tenant-reconciler
        fieldPaths:
          - metadata.namespace
      # Set RoleBinding namespace and subject namespace.
      - select:
          kind: RoleBinding
          name: tenant-reconciler
        fieldPaths:
          - metadata.namespace
          - subjects.[name=tenant-reconciler].namespace
